# Generated by Django 4.0.4 on 2022-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='usertobook',
            name='status',
            field=models.CharField(choices=[('issued', 'ISSUED'), ('returned', 'RETURNED')], default='issued', max_length=30),
        ),
    ]
