# Generated by Django 4.0.4 on 2022-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_book_status_usertobook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertobook',
            name='issued_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertobook',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
