# Generated by Django 4.0.4 on 2022-05-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usertobook_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertobook',
            old_name='price',
            new_name='user_price',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=88.0, max_digits=6),
            preserve_default=False,
        ),
    ]
